const sonar = require( 'sonarqube-build-breaker' );

let token = 'squ_e92d7f3d2c09335a4926e6924773b8d37b9fd5d9'; //best way is process.env.SONAR_TOKEN;
let server = 'http://13.38.217.8/:9000'; //best way is process.env.SONAR_SERVER;
let file = './.scannerwork/report-task.txt'; // this is a file generated by sonar-scanner execution

sonar.checkQuality( server, file, token );